# Generated by Django 4.0.4 on 2022-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(default=True, max_length=255, verbose_name='URL'),
        ),
    ]
